const initialState = [
  {
    id: "topcloth_1",
    type: "topclothes",
    name: "Top Cloth 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/topcloth1_show.jpg",
    imgSrc_png: "/img/dressingRoom/topcloth1.png",
  },
  {
    id: "topcloth_2",
    type: "topclothes",
    name: "Top Cloth 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/topcloth2_show.jpg",
    imgSrc_png: "/img/dressingRoom/topcloth2.png",
  },
  {
    id: "topcloth_3",
    type: "topclothes",
    name: "Top Cloth 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/topcloth3_show.jpg",
    imgSrc_png: "/img/dressingRoom/topcloth3.png",
  },
  {
    id: "topcloth_4",
    type: "topclothes",
    name: "Top Cloth 4",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/topcloth4_show.jpg",
    imgSrc_png: "/img/dressingRoom/topcloth4.png",
  },
  {
    id: "topcloth_5",
    type: "topclothes",
    name: "Top Cloth 5",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/topcloth5_show.jpg",
    imgSrc_png: "/img/dressingRoom/topcloth5.png",
  },
  {
    id: "topcloth_6",
    type: "topclothes",
    name: "Top Cloth ",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/topcloth6_show.jpg",
    imgSrc_png: "/img/dressingRoom/topcloth6.png",
  },
  {
    id: "botcloth_1",
    type: "botclothes",
    name: "Bot Cloth 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/botcloth1_show.jpg",
    imgSrc_png: "/img/dressingRoom/botcloth1.png",
  },
  {
    id: "botcloth_2",
    type: "botclothes",
    name: "Bot Cloth 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/botcloth2_show.jpg",
    imgSrc_png: "/img/dressingRoom/botcloth2.png",
  },
  {
    id: "botcloth_3",
    type: "botclothes",
    name: "Bot Cloth 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/botcloth3_show.jpg",
    imgSrc_png: "/img/dressingRoom/botcloth3.png",
  },
  {
    id: "botcloth_4",
    type: "botclothes",
    name: "Bot Cloth 4",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/botcloth4_show.jpg",
    imgSrc_png: "/img/dressingRoom/botcloth4.png",
  },
  {
    id: "botcloth_5",
    type: "botclothes",
    name: "Bot Cloth 5",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/botcloth5_show.jpg",
    imgSrc_png: "/img/dressingRoom/botcloth5.png",
  },
  {
    id: "shoes_1",
    type: "shoes",
    name: "Shoes 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/shoes1_show.jpg",
    imgSrc_png: "/img/dressingRoom/shoes1.png",
  },
  {
    id: "shoes_2",
    type: "shoes",
    name: "Shoes 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/shoes2_show.jpg",
    imgSrc_png: "/img/dressingRoom/shoes2.png",
  },
  {
    id: "shoes_3",
    type: "shoes",
    name: "Shoes 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/shoes3_show.jpg",
    imgSrc_png: "/img/dressingRoom/shoes3.png",
  },
  {
    id: "shoes_4",
    type: "shoes",
    name: "Shoes 4",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/shoes4_show.jpg",
    imgSrc_png: "/img/dressingRoom/shoes4.png",
  },
  {
    id: "shoes_5",
    type: "shoes",
    name: "Shoes 5",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/shoes5_show.jpg",
    imgSrc_png: "/img/dressingRoom/shoes5.png",
  },
  {
    id: "handbag_1",
    type: "handbags",
    name: "Handbag 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/handbag1_show.jpg",
    imgSrc_png: "/img/dressingRoom/handbag1.png",
  },
  {
    id: "handbag_2",
    type: "handbags",
    name: "Handbag 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/handbag2_show.jpg",
    imgSrc_png: "/img/dressingRoom/handbag2.png",
  },
  {
    id: "handbag_3",
    type: "handbags",
    name: "Handbag 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/handbag3_show.jpg",
    imgSrc_png: "/img/dressingRoom/handbag3.png",
  },
  {
    id: "necklace_1",
    type: "necklaces",
    name: "Necklace 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/necklace1_show.jpg",
    imgSrc_png: "/img/dressingRoom/necklace1.png",
  },
  {
    id: "necklace_2",
    type: "necklaces",
    name: "Necklace 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/necklace2_show.jpg",
    imgSrc_png: "/img/dressingRoom/necklace2.png",
  },
  {
    id: "necklace_3",
    type: "necklaces",
    name: "Necklace 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/necklace3_show.jpg",
    imgSrc_png: "/img/dressingRoom/necklace3.png",
  },
  {
    id: "hairstyle_1",
    type: "hairstyle",
    name: "Hairstyle 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/hairstyle1_show.jpg",
    imgSrc_png: "/img/dressingRoom/hairstyle1.png",
  },
  {
    id: "hairstyle_2",
    type: "hairstyle",
    name: "Hairstyle 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/hairstyle2_show.jpg",
    imgSrc_png: "/img/dressingRoom/hairstyle2.png",
  },
  {
    id: "hairstyle_3",
    type: "hairstyle",
    name: "Hairstyle 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/hairstyle3_show.jpg",
    imgSrc_png: "/img/dressingRoom/hairstyle3.png",
  },
  {
    id: "background_1",
    type: "background",
    name: "Background 1",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/background1_show.jpg",
    imgSrc_png: "/img/dressingRoom/background1.jpg",
  },
  {
    id: "background_2",
    type: "background",
    name: "Background 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/background2_show.jpg",
    imgSrc_png: "/img/dressingRoom/background2.jpg",
  },
  {
    id: "background_3",
    type: "background",
    name: "Background 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/background3_show.jpg",
    imgSrc_png: "/img/dressingRoom/background3.jpg",
  },
  {
    id: "background_4",
    type: "background",
    name: "Background 4",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.",
    imgSrc_jpg: "/img/dressingRoom/background4_show.jpg",
    imgSrc_png: "/img/dressingRoom/background4.jpg",
  },
];

const dressingRoomReducer = (state = initialState)=>{
  return state
}
export default dressingRoomReducer